rvm:
- 2.0.0
env:
  secure: GT+apq58El6Xgvx+iq9r8aehtkOfgMKnpnmeTeiCBLnNKXcoS5kgPLUd9MUGg16A+G4cDaQvGLeXZxC3uSLIRp7DEe28Ol+9iWlOPOi8NKNjJ2MLCRmmCA9AL2IwV/zU6rYNpfa5cIuYWsxfN/NApzS6wkofz5Dozlq65COFmck=